apiVersion: v1
data:
  APP_VERSION: "{{ .Values.version }}"
kind: ConfigMap
metadata:
  name: chiaretto-app2-version
---
apiVersion: v1
data:
  APP_ENV: "{{ .Values.env }}"
kind: ConfigMap
metadata:
  name: chiaretto-app2-environment

