apiVersion: v1
kind: Service
metadata:
  labels:
    app: chiaretto-app2
    app.kubernetes.io/component: chiaretto-app2
    app.kubernetes.io/instance: chiaretto-app2
  name: chiaretto-app2
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deploymentconfig: chiaretto-app2
  sessionAffinity: None
  type: ClusterIP
